---
title: "regional violence project"
output: html_notebook
editor_options: 
  chunk_output_type: console
---
```{r}
# loading required libraries
library(rnaturalearth)
library(rnaturalearthdata)
library(tidyverse)
library(sf)
library(rgeos)
library(ggspatial)
library(ggrepel)
library(sp)
```

```{r}
# obtaining the vector files

# grabbing the world polygons
world = ne_countries(scale = "medium", returnclass = "sf", type = "countries")

# from the world file, extracting only the Central American countries.
ca = filter(world, (subregion == "Central America" & name_long != "Mexico"))

# filter out the C.A. countries from the world data.
world = filter(world, (subregion != "Central America" | name_long == "Mexico"))

# building the vector of centroids. This is needed for label placement.
world_points = cbind(world, st_coordinates(st_centroid(world$geometry)))
ca_points = cbind(ca, st_coordinates(st_centroid(ca$geometry)))

# grabbing the oceans polygons
oceans = ne_download(scale = 50, type = 'ocean', category = 'physical', returnclass = "sf")

#testing
# ggplot(data=oceans)+
#   geom_sf()
```

```{r}
# renaming the data frame into something more manageable!
ca_df = X2018_03_13_2021_03_15_Central_America

# In this next line I'm building a table of statistics we can map.
ca_table = table(ca_df$sub_event_type, ca_df$country)
ca_table = as.data.frame(ca_table)
names(ca_table)[1] = 'type'
names(ca_table)[2] = 'country'

# let's say were only interested in "attack"
ca_table = filter(ca_table, type == "Attack")

# building the basemap

ggplot() +  

# Attention must be paid to the order in which shapefiles are added, because
# layers added later will overlap layers added earlier.
# For this reason, we're adding the oceans layer first.
geom_sf(data=oceans, fill= 'steelblue1') +

# Adding the layer that has the names of the countries outside the area of interest.     
  geom_sf(data=world, fill='gray') +
      geom_text(data=world_points, aes(x=X, y=Y, label = name),
      color = 'grey30',
      check_overlap = TRUE)+
  
  # This next line adds the Central America shapefile to the map.
  geom_sf(data=ca, aes(fill = ca_table$Freq)) +
  
  # This next line labels the Central American countries
  geom_text(data = ca_points, aes(x=X, y=Y, label = name),
            color = "black",
            fontface = 'bold',
            check_overlap = TRUE)+
  
  # Plotting the data
  #geom_map(data=ca_table, map = ca, aes(fill=Freq, map_id = country))+
  
  # zooming in on the area of interest
  coord_sf(xlim = c(-93, -76), ylim = c(6, 19))+
  
  # In this section I am removing the grid lines, tick marks, and labels. 
  # Since this is a thematic map, communicating latitude and longitude 
  # detract from the map's message. 
  xlab(element_blank())+
  ylab(element_blank())+
  theme(
    axis.ticks = element_blank(),
    axis.text = element_blank(),
    panel.grid = element_blank()
      )+
  ggtitle('An Appropriate Title Here')

```

